String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'vanilla birthday',
    '%4'                    : 'bubblegum pink',
    '%8'                    : 'sunshine vanilla',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'vanilla birthday',
    '%p4'                   : 'bubblegum pink',
    '%p8'                   : 'sunshine vanilla',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : '2017 Confetti Vanilla',
    '%p8192'                : 'Rainbow'
  }

});
