FullScreenMario.FullScreenMario.settings.audio = {
    "directory": "Sounds",
    "fileTypes": ["mp3", "ogg"],
    "library": {
        "Sounds": [
            "Bowser Falls",
            "Bowser Fires",
            "Break Block",
            "Bump",
            "Coin",
            "Ending",
            "Fail",
            "Fireball",
            "Firework",
            "Flagpole",
            "Gain Life",
            "Game Over 2",
            "Game Over",
            "Hurry",
            "Jump Small",
            "Jump Super",
            "Kick",
            "Level Complete",
            "Player Dies",
            "Pause",
            "Pipe",
            "Power Down",
            "Powerup Appears",
            "Powerup",
            "Stage Clear",
            "Vine Emerging",
            "World Clear",
            "You Dead"
        ],
        "Themes": [
            "Castle",
            "Overworld",
            "Underwater",
            "Underworld",
            "Star",
            "Sky",
            "Hurry Castle",
            "Hurry Overworld",
            "Hurry Underwater",
            "Hurry Underworld",
            "Hurry Star",
            "Hurry Sky"
        ]
    }
};
